### ISSUE TITLE
Make screw hole slightly larger?

### ISSUE THREAD

**Issue by amaiorano** [jeffqchen/SNES2VGA#1]
Hello,

I printed `top.stl` and found that my M3x20mm screw head was slightly too large to fit in the hole:

![image](https://github.com/jeffqchen/SNES2VGA/assets/6893883/391fc56b-5a91-4e00-bee5-a1267973be76)

I ended up modifying the STL in Fusion and made it slightly larger, with a diameter of 5.8mm:

![image](https://github.com/jeffqchen/SNES2VGA/assets/6893883/8035eb98-f54a-495e-b1c7-114ae38fcd96)

![image](https://github.com/jeffqchen/SNES2VGA/assets/6893883/2d2cc34f-fa4e-47d2-8b9f-093a44191de8)

![image](https://github.com/jeffqchen/SNES2VGA/assets/6893883/49b31a4e-9e49-4a4f-aae3-4197172e4fcc)

I bought [my screw kit on amazon.ca](https://www.amazon.ca/gp/product/B09TSKT4CZ/ref=ppx_yo_dt_b_search_asin_image?ie=UTF8&psc=1), so I suspect I'm not the only one who may run into this issue. Would it possible for you to make the holes slightly larger in the official design?

P.S. Thank you for this awesome project!

**Comment by jeffqchen** [comment]
I expected people to follow the link and purchase the proper (and nice-looking) screws I used in the design. You are welcome to make the hole bigger for yourself.

**Comment by amaiorano** [comment]
> I expected people to follow the link and purchase the proper (and nice-looking) screws I used in the design. You are welcome to make the hole bigger for yourself.

Oh, because the [page you linked with the screws](https://github.com/jeffqchen/JeffParts/blob/main/Parts/M2%20M3%20Hex%20Screw%20%26%20Nut/info.md) shows multiple options of kits one can buy, including one that looks a lot like the one I already had (the last one).

**Comment by jeffqchen** [comment]
My bad. I don't think I've used the last type in any of my designs. Maybe I included it there just to offer more information. I'll remove it later.

**Comment by amaiorano** [comment]
Fair enough, it's your design. Thanks again.
